🚧 Raise minimum numpy version to 1.22
This is required by numba which gets installer together with pygflotaran
See error
ImportError: Numba needs NumPy 1.22 or greater. Got NumPy 1.21.