🩹 Fix incompatibility of plot_data_and_fits with matplotlib>=3.8 (#275)
* 🚧 Add requirements_min.txt

* 🚇🧪 Add job to run tests with requirements_min

* ✨ Add matplotlib < 3.8 and >=3.8 compatible cycler call function

* 🩹 Use get_next_cycler_color in plot_data_and_fits to advance cycler

* 🚧 Raise minimum numpy version to 1.22

This is required by numba which gets installer together with pygflotaran
See error
ImportError: Numba needs NumPy 1.22 or greater. Got NumPy 1.21.

* 🚧📚 Added changes to changelog